/*
 * Launa Bucher-Austin
 * This program will perform all math operations from the inputted numbers.
 * April 3 2020
 */

/**
 *
 * @author launa
 */
public class magmathfrm extends javax.swing.JFrame {

    /**
     * Creates new form magmathfrm
     */
    public magmathfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tltlbl = new javax.swing.JLabel();
        maxlbl = new javax.swing.JLabel();
        minlbl = new javax.swing.JLabel();
        powlbl = new javax.swing.JLabel();
        hypotlbl = new javax.swing.JLabel();
        ceilbl = new javax.swing.JLabel();
        floorlbl = new javax.swing.JLabel();
        sqrtlbl = new javax.swing.JLabel();
        radianlbl = new javax.swing.JLabel();
        maxtxt = new javax.swing.JTextField();
        maxtxt2 = new javax.swing.JTextField();
        mintxt = new javax.swing.JTextField();
        mintxt2 = new javax.swing.JTextField();
        powtxt = new javax.swing.JTextField();
        powtxt2 = new javax.swing.JTextField();
        hypottxt = new javax.swing.JTextField();
        hypottxt2 = new javax.swing.JTextField();
        ceiltxt = new javax.swing.JTextField();
        floortxt = new javax.swing.JTextField();
        sqrttxt = new javax.swing.JTextField();
        radiantxt = new javax.swing.JTextField();
        maxbtn = new javax.swing.JButton();
        minbtn = new javax.swing.JButton();
        powbtn = new javax.swing.JButton();
        hypotbtn = new javax.swing.JButton();
        ceilbtn = new javax.swing.JButton();
        floorbtn = new javax.swing.JButton();
        sqrtbtn = new javax.swing.JButton();
        radianbtn = new javax.swing.JButton();
        maxanslbl = new javax.swing.JLabel();
        minanslbl = new javax.swing.JLabel();
        powanslbl = new javax.swing.JLabel();
        hypotanslbl = new javax.swing.JLabel();
        ceilanslbl = new javax.swing.JLabel();
        flooranslbl = new javax.swing.JLabel();
        sqrtanslbl = new javax.swing.JLabel();
        radiananslbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tltlbl.setText("Magical Math Methods");

        maxlbl.setText("Enter two number and click the button. The program will display the largest of the two numbers :");

        minlbl.setText("Enter two numbers and click the button. The program will display the smallest of the two numbers :  ");

        powlbl.setText("Enter two numbers and click the button. The program will display the first number to the power of the second : ");

        hypotlbl.setText("Enter two sides to a right angle triangle. The program will display the hypotenuse of the triangle :");

        ceilbl.setText("Enter a decimal value. The program will display the value rounded up to the nearest integer : ");

        floorlbl.setText("Enter a decimal value. The program will display the value rounded down to the nearest integer :");

        sqrtlbl.setText("Enter an integer. The program will display the square root of the integer : ");

        radianlbl.setText("Enter an angle in degrees. The program will displat the angle in radians :");

        maxtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxtxtActionPerformed(evt);
            }
        });

        mintxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mintxtActionPerformed(evt);
            }
        });

        mintxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mintxt2ActionPerformed(evt);
            }
        });

        maxbtn.setText("Largest");
        maxbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxbtnActionPerformed(evt);
            }
        });

        minbtn.setText("Smallest");
        minbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minbtnActionPerformed(evt);
            }
        });

        powbtn.setText("To the power of..");
        powbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powbtnActionPerformed(evt);
            }
        });

        hypotbtn.setText("Hypotenuse");
        hypotbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypotbtnActionPerformed(evt);
            }
        });

        ceilbtn.setText("Rounded up");
        ceilbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceilbtnActionPerformed(evt);
            }
        });

        floorbtn.setText("Rounded down");
        floorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorbtnActionPerformed(evt);
            }
        });

        sqrtbtn.setText("Square Root");
        sqrtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtbtnActionPerformed(evt);
            }
        });

        radianbtn.setText("In Radians");
        radianbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radianbtnActionPerformed(evt);
            }
        });

        maxanslbl.setText("...");

        minanslbl.setText("...");

        powanslbl.setText("...");

        hypotanslbl.setText("...");

        ceilanslbl.setText("...");

        flooranslbl.setText("...");

        sqrtanslbl.setText("...");

        radiananslbl.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(powlbl)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxlbl)
                            .addComponent(tltlbl)
                            .addComponent(minlbl)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(powtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hypottxt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sqrtlbl)
                                    .addComponent(radianlbl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(mintxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(minbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(minanslbl))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(powtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(powbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(powanslbl))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(floortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(97, 97, 97)
                                        .addComponent(floorbtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(flooranslbl))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(sqrttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(94, 94, 94)
                                        .addComponent(sqrtbtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(sqrtanslbl))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(radiantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100)
                                        .addComponent(radianbtn)
                                        .addGap(33, 33, 33)
                                        .addComponent(radiananslbl))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(hypottxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hypotbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hypotanslbl))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(ceilbl))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maxtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maxbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maxanslbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ceiltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(105, 105, 105)
                                        .addComponent(ceilbtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(ceilanslbl))
                                    .addComponent(floorlbl)))))
                    .addComponent(hypotlbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(tltlbl)
                .addGap(18, 18, 18)
                .addComponent(maxlbl)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxbtn)
                    .addComponent(maxanslbl))
                .addGap(12, 12, 12)
                .addComponent(minlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mintxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mintxt)
                    .addComponent(minbtn)
                    .addComponent(minanslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(powlbl)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(powtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(powtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(powbtn)
                    .addComponent(powanslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hypotlbl)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hypottxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hypotbtn)
                    .addComponent(hypottxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hypotanslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ceilbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ceiltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceilbtn)
                    .addComponent(ceilanslbl))
                .addGap(1, 1, 1)
                .addComponent(floorlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(floorbtn)
                        .addComponent(flooranslbl))
                    .addComponent(floortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sqrtlbl)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sqrtbtn)
                        .addComponent(sqrtanslbl))
                    .addComponent(sqrttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radianlbl)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiantxt)
                    .addComponent(radianbtn)
                    .addComponent(radiananslbl))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maxtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxtxtActionPerformed

    private void mintxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mintxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mintxtActionPerformed

    private void mintxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mintxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mintxt2ActionPerformed

    private void maxbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxbtnActionPerformed
        // declare variables
        double num1;
        double num2;
        double max;
        
        num1 = Integer.parseInt(maxtxt.getText());
        num2 = Integer.parseInt(maxtxt2.getText());
        
        max = Math.max (num1, num2);
        maxanslbl.setText (String.valueOf(max));
    }//GEN-LAST:event_maxbtnActionPerformed

    private void minbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minbtnActionPerformed
       // declare variables
        double num1;
        double num2; 
        double min;
        
        num1 = Integer.parseInt(mintxt.getText());
        num2 = Integer.parseInt(mintxt2.getText());
        
        min = Math.min (num1, num2);
        minanslbl.setText(String.valueOf(min));
        
        
    }//GEN-LAST:event_minbtnActionPerformed

    private void powbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powbtnActionPerformed
       // declare variables
        double num1; 
       double num2; 
       double pow;
       num1 = Integer.parseInt(powtxt.getText());
       num2 = Integer.parseInt(powtxt2.getText());
       
       pow = Math.pow (num1, num2);
       powanslbl.setText(String.valueOf(pow));
      
    }//GEN-LAST:event_powbtnActionPerformed

    private void hypotbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypotbtnActionPerformed
       // declare variables
       double num1; 
       double num2;
       double hypot; 
       num1 = Integer.parseInt(hypottxt.getText());
       num2 = Integer.parseInt(hypottxt2.getText());
       
       hypot = Math.hypot(num1, num2);
       hypotanslbl.setText(String.valueOf(hypot));
    }//GEN-LAST:event_hypotbtnActionPerformed

    private void ceilbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceilbtnActionPerformed
        // declare variables
        double num1; 
        double ceil; 
        
        num1 = Integer.parseInt(ceiltxt.getText());
        ceil = Math.ceil(num1);
        ceilanslbl.setText(String.valueOf(ceil));
        
    }//GEN-LAST:event_ceilbtnActionPerformed

    private void floorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorbtnActionPerformed
       // declare variables
        double num1;
        double floor;
        
        num1= Integer.parseInt(floortxt.getText());
        floor = Math.floor(num1);
        
        flooranslbl.setText(String.valueOf(floor));
    }//GEN-LAST:event_floorbtnActionPerformed

    private void sqrtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtbtnActionPerformed
      // declare variables
        double num1;
        double sqrt;
        
        num1 = Integer.parseInt(sqrttxt.getText());
        sqrt = Math.sqrt(num1);
        
        sqrtanslbl.setText(String.valueOf(sqrt));
        
    }//GEN-LAST:event_sqrtbtnActionPerformed

    private void radianbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radianbtnActionPerformed
      // declare variables
        double num1; 
        double radian; 
        
        num1 = Integer.parseInt(radiantxt.getText());
        radian = Math.toRadians(num1);
        
        radiananslbl.setText(String.valueOf(radian));
    }//GEN-LAST:event_radianbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(magmathfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(magmathfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(magmathfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(magmathfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new magmathfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ceilanslbl;
    private javax.swing.JLabel ceilbl;
    private javax.swing.JButton ceilbtn;
    private javax.swing.JTextField ceiltxt;
    private javax.swing.JLabel flooranslbl;
    private javax.swing.JButton floorbtn;
    private javax.swing.JLabel floorlbl;
    private javax.swing.JTextField floortxt;
    private javax.swing.JLabel hypotanslbl;
    private javax.swing.JButton hypotbtn;
    private javax.swing.JLabel hypotlbl;
    private javax.swing.JTextField hypottxt;
    private javax.swing.JTextField hypottxt2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel maxanslbl;
    private javax.swing.JButton maxbtn;
    private javax.swing.JLabel maxlbl;
    private javax.swing.JTextField maxtxt;
    private javax.swing.JTextField maxtxt2;
    private javax.swing.JLabel minanslbl;
    private javax.swing.JButton minbtn;
    private javax.swing.JLabel minlbl;
    private javax.swing.JTextField mintxt;
    private javax.swing.JTextField mintxt2;
    private javax.swing.JLabel powanslbl;
    private javax.swing.JButton powbtn;
    private javax.swing.JLabel powlbl;
    private javax.swing.JTextField powtxt;
    private javax.swing.JTextField powtxt2;
    private javax.swing.JLabel radiananslbl;
    private javax.swing.JButton radianbtn;
    private javax.swing.JLabel radianlbl;
    private javax.swing.JTextField radiantxt;
    private javax.swing.JLabel sqrtanslbl;
    private javax.swing.JButton sqrtbtn;
    private javax.swing.JLabel sqrtlbl;
    private javax.swing.JTextField sqrttxt;
    private javax.swing.JLabel tltlbl;
    // End of variables declaration//GEN-END:variables
}
